version: '3'
services:
  redis:
    image: "redis"
    volumes:
      - redis-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes

  scraper:
    build: ./ugscraper
    depends_on:
      - redis
    volumes:
      - ./logs:/usr/src/app/logs

volumes:
  redis-data:
